name: consultacep
description: Aplicativo para consulta de CEPs utilizando a API ViaCEP.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

flutter:
  uses-material-design: true
